logging:
  level: INFO
  format: "<r>{time}</r>: <lvl>{level}</lvl> <g>{message}</g>"
  rotate: 1 days
  retention: 15 days
  path: data/logs/xtracking.log
time:
  zone: 'Asia/Shanghai'
  datetime_format: '%Y-%m-%d %H:%M:%S'
  date_format: '%Y-%m-%d'

database:
  host: 127.0.0.1
  port: 5432
  user: odoo
  password: odoo
  name: test # 数据库名称

sync:
#  source_dsn: "postgresql://odoo:odoo@localhost/test"
  source:
    host: 10.1.10.3
    port: 1433
    database: sndb
    username: sn
    password: Empower@67601510
  sink_dsn: "postgresql://odoo:odoo@localhost/test"
  sync_interval: 5 # 单位分钟
