-- sndb.dbo.sncx definition

-- Drop table

-- DROP TABLE sndb.dbo.sncx;

CREATE TABLE sndb.dbo.sncx (
	ID int IDENTITY(1,1) NOT NULL,
	FSERIALID int NOT NULL,
	FNUMBER nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL,
	mFNUMBER nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL,
	FSN nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	F_WISY_ZBTIME int NULL,
	FDESCRIPTION nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	oblFNAME nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	orglFNAME nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	FSTATE int NULL,
	FBILLNO nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	FBILLDATE datetime NULL,
	FORDERNO nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	FINPUTDATE datetime NULL,
	sulFNAME nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	culFNAME nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	FLOT nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	stlFNAME nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	FCREATEDATE datetime NULL,
	FPRODUCEDATE datetime NULL,
	FSTARTDATE datetime NULL,
	FENDDATE datetime NULL,
	FSALEDATE datetime NULL,
	FLAG int NULL,
	CONSTRAINT PK_sncx PRIMARY KEY (ID)
);
 CREATE NONCLUSTERED INDEX FNUMBER ON dbo.sncx (  FNUMBER ASC  )
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FSERIALID ON dbo.sncx (  FSERIALID ASC  )
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX mFNUMBER ON dbo.sncx (  mFNUMBER ASC  )
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;