name: Onesphere CI Workflow

on:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get committer details
        run: |
          echo Actor: ${{ github.actor }}
          echo Committed By: ${{ github.event.commits[0].author.name }}
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          lfs: 'true'
          token: ${{ secrets.PAT }}
      - name: set time
        run: |
          echo "TIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: docker login github package
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAT }}
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ethermeta-org/xtracking:latest
            ghcr.io/ethermeta-org/xtracking:${{ env.TIME }}
          file: Dockerfile